import React from "react";
import { CardStyle } from "../types";
import { IndexStyleProps, pad, formatStars } from "./cardStyleProps";

type Variant = React.FC<IndexStyleProps>;

const base = (p: IndexStyleProps, cls = "", extra?: React.CSSProperties) => ({
  className: `w-full h-full rounded-2xl relative overflow-hidden flex flex-col ${cls}`,
  style: {
    backgroundColor: p.theme.cardBg,
    color: p.theme.textColor,
    ...extra,
  },
});

const Classic: Variant = (p) => (
  <div {...base(p, "py-[3%] px-[4%] shadow-inner")}>
    <div className="mb-4 text-center">
      <div className="inline-block px-3 py-1 rounded-full bg-white/5 border border-white/10 text-[9px] font-black tracking-[0.2em] uppercase mb-2 opacity-60">
        Daily Ranking
      </div>
      <h2 className="text-2xl font-black tracking-tighter leading-none">GitHub Trending</h2>
      <p className="text-[10px] font-mono opacity-30 mt-1.5">TOP 15 PROJECTS • {p.displayDate}</p>
    </div>
    <div className="flex-1 flex flex-col justify-between py-1">
      {p.trendingData.slice(0, 15).map((item, idx) => (
        <div key={item.id || idx} className="flex items-center gap-3">
          <span className="w-6 text-sm font-mono opacity-20 font-black">{pad(idx)}</span>
          <span className="flex-1 text-sm font-bold tracking-tight truncate">{item.title}</span>
          <span
            className="text-xs font-mono font-black"
            style={{ color: idx < 3 ? p.theme.accentColor : "inherit", opacity: idx < 3 ? 1 : 0.3 }}
          >
            {formatStars(item.stars || "")} 今日:{item.starsToday || "0"}
          </span>
        </div>
      ))}
    </div>
    <div className="mt-4 pt-3 border-t border-white/5 flex justify-between items-center">
      <div className="opacity-30">
        <div className="text-[9px] font-black tracking-widest uppercase">Generated by @{p.authorName}</div>
        <div className="font-mono text-[9px] uppercase tracking-widest">{p.timeText}</div>
      </div>
      <img
        src="/my-avatar.jpg"
        alt="author"
        crossOrigin="anonymous"
        className="w-14 h-14 rounded-full border-2 border-white/10 shadow-md object-cover"
        referrerPolicy="no-referrer"
      />
    </div>
  </div>
);

const Poster: Variant = (p) => (
  <div {...base(p, "px-[5%] py-[6%]")}>
    <div className="flex items-center justify-between mb-2">
      <span className="text-[10px] font-black tracking-[0.3em] uppercase opacity-50">Daily Ranking</span>
      <span className="text-[10px] font-mono opacity-40">{p.displayDate}</span>
    </div>
    <h2 className="text-[clamp(2.4rem,9vw,4.2rem)] font-black leading-[0.95] tracking-tighter">
      GitHub
      <br />
      <span style={{ color: p.theme.accentColor }}>Trending</span>
    </h2>
    <div className="mt-3 h-[3px] w-16 rounded-full" style={{ backgroundColor: p.theme.accentColor }} />
    <div className="flex-1 flex flex-col justify-center gap-2.5 py-2">
      {p.trendingData.slice(0, 5).map((item, idx) => (
        <div key={item.id || idx} className="flex items-center gap-3">
          <span className="text-2xl font-black font-mono" style={{ color: idx === 0 ? p.theme.accentColor : undefined, opacity: idx === 0 ? 1 : 0.45 }}>
            {pad(idx)}
          </span>
          <span className="flex-1 text-base font-bold tracking-tight truncate">{item.title}</span>
          <span className="text-sm font-mono font-black opacity-60">{formatStars(item.stars || "")}</span>
        </div>
      ))}
    </div>
    <div className="flex items-center justify-between pt-4 border-t border-white/10">
      <div className="text-[10px] font-black tracking-widest uppercase opacity-50">Generated by @{p.authorName}</div>
      <div className="font-mono text-[10px] uppercase tracking-widest opacity-40">{p.timeText}</div>
    </div>
  </div>
);

const Terminal: Variant = (p) => (
  <div {...base(p, "font-mono")}>
    <div className="flex items-center gap-1.5 px-4 py-3 bg-white/[0.06] border-b border-white/10">
      <span className="w-2.5 h-2.5 rounded-full bg-[#ff5f56]" />
      <span className="w-2.5 h-2.5 rounded-full bg-[#ffbd2e]" />
      <span className="w-2.5 h-2.5 rounded-full bg-[#27c93f]" />
      <span className="ml-3 text-[12px] opacity-50">github-trending — zsh</span>
    </div>
    <div className="flex-1 px-5 py-4 flex flex-col gap-2.5 overflow-hidden">
      <div className="opacity-50 text-[12px]">$ ./trend.sh --top 15 --date {p.displayDate}</div>
      <div className="text-[13px] opacity-70 mb-1" style={{ color: p.theme.accentColor }}># 今日 GitHub 爆火项目 Top{p.trendingData.length}</div>
      {p.trendingData.slice(0, 8).map((item, idx) => (
        <div key={item.id || idx} className="text-[13px] leading-relaxed">
          <span style={{ color: p.theme.accentColor }}>#{pad(idx)}</span>{" "}
          <span className="font-bold">{item.title}</span>{" "}
          <span className="opacity-70">★{formatStars(item.stars || "")}</span>{" "}
          <span className="opacity-50">+{item.starsToday || "0"}</span>
        </div>
      ))}
      <div className="text-[13px] opacity-50 mt-auto">$ _</div>
    </div>
    <div className="px-5 py-3 border-t border-white/10 flex justify-between text-[11px] opacity-50">
      <span>generated by @{p.authorName}</span>
      <span>{p.timeText}</span>
    </div>
  </div>
);

const Magazine: Variant = (p) => (
  <div {...base(p, "px-[5%] py-[5.5%]")}>
    <div className="flex items-center justify-between">
      <span className="text-[9px] font-black tracking-[0.35em] uppercase opacity-40">The Daily Ranking</span>
      <span className="text-[9px] font-mono opacity-40">{p.displayDate}</span>
    </div>
    <h2 className="mt-2.5 text-[clamp(1.6rem,5.5vw,2.8rem)] font-black tracking-tight">GitHub Trending</h2>
    <div className="mt-2 h-px w-full bg-white/20" />
    <div className="flex-1 flex flex-col justify-between py-2">
      {p.trendingData.slice(0, 15).map((item, idx) => (
        <div key={item.id || idx} className="flex items-baseline gap-2">
          <span className="w-6 font-mono text-[11px] opacity-30 font-bold">{pad(idx)}</span>
          <span className="flex-1 text-sm font-semibold tracking-tight truncate">{item.title}</span>
          <span className="text-[10px] font-mono opacity-40">{item.starsToday ? `今日 +${item.starsToday}` : ""}</span>
          <span className="text-xs font-mono font-bold opacity-70">{formatStars(item.stars || "")}</span>
        </div>
      ))}
    </div>
    <div className="pt-3 border-t border-white/20 flex justify-between items-center">
      <span className="text-[9px] font-black tracking-widest uppercase opacity-50">Generated by @{p.authorName}</span>
      <span className="font-mono text-[9px] uppercase tracking-widest opacity-40">{p.timeText}</span>
    </div>
  </div>
);

const Databar: Variant = (p) => {
  const max = Math.max(...p.trendingData.slice(0, 8).map((i) => parseFloat(String(i.stars).replace(/k/gi, "").replace(/,/g, "")) || 0), 1);
  const width = (s?: string) => `${Math.max(((parseFloat(String(s).replace(/k/gi, "").replace(/,/g, "")) || 0) / max) * 100, 1.5)}%`;
  return (
    <div {...base(p, "px-[7%] py-[6%]", { backgroundColor: "#ffffff", color: "#18181b" })}>
      <div className="flex justify-between items-center mb-3">
        <span className="font-mono text-[9px] tracking-[0.25em] uppercase opacity-50">Top {p.trendingData.length} · GitHub Trending</span>
        <span className="font-mono text-[9px] opacity-40">{p.displayDate.slice(0, 6)}</span>
      </div>
      <div className="w-full h-[2px] bg-zinc-900" />
      <div className="flex-1 flex flex-col gap-4 py-3">
        {p.trendingData.slice(0, 8).map((item, idx) => (
          <div key={item.id || idx}>
            <div className="flex justify-between text-[13px] font-bold mb-1">
              <span className="truncate">{pad(idx)} {item.title.split("/")[1] || item.title}</span>
              <span className="font-mono">{formatStars(item.stars || "")}</span>
            </div>
            <div className="h-[10px] rounded-full bg-zinc-100">
              <div className="h-full rounded-full" style={{ width: width(item.stars), backgroundColor: idx === 0 ? p.theme.accentColor : "#6366f1" }} />
            </div>
          </div>
        ))}
      </div>
      <div className="pt-3 border-t border-zinc-200 flex justify-between text-[11px] uppercase tracking-widest opacity-50">
        <span className="font-bold">Generated by @{p.authorName}</span>
        <span className="font-mono">{p.timeText}</span>
      </div>
    </div>
  );
};

const Cardstack: Variant = (p) => (
  <div {...base(p, "gap-2.5 px-[6%] py-[6%]")}>
    <div className="flex justify-between items-center">
      <span className="text-[9px] font-black tracking-[0.25em] uppercase opacity-60">Daily Ranking</span>
      <span className="font-mono text-[9px] opacity-40">{p.displayDate}</span>
    </div>
    <div className="flex-1 flex flex-col gap-2 overflow-hidden">
      {p.trendingData.slice(0, 8).map((item, idx) => (
        <div key={item.id || idx} className="flex items-center gap-3 rounded-xl bg-white/10 border border-white/10 px-3 py-2">
          <span className="w-7 text-base font-black font-mono" style={{ color: idx === 0 ? p.theme.accentColor : undefined, opacity: idx === 0 ? 1 : 0.5 }}>
            {pad(idx)}
          </span>
          <span className="flex-1 text-[15px] font-bold truncate">{item.title}</span>
          <span className="px-2 py-0.5 rounded-md text-[11px] font-mono font-bold" style={{ backgroundColor: p.theme.accentColor + "22", color: p.theme.accentColor }}>
            {formatStars(item.stars || "")}
          </span>
        </div>
      ))}
    </div>
    <div className="flex justify-between pt-2 border-t border-white/10 text-[11px] uppercase tracking-widest opacity-50">
      <span className="font-bold">@{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Glass: Variant = (p) => (
  <div {...base(p, "gap-2.5 px-[4%] py-[5%]")}>
    <div className="flex items-center justify-between rounded-2xl border border-white/15 bg-white/10 backdrop-blur-md px-4 py-2.5">
      <div>
        <div className="text-[9px] font-black tracking-[0.25em] uppercase opacity-60">Daily Ranking</div>
        <div className="text-lg font-black leading-none mt-1">GitHub Trending</div>
      </div>
      <div className="text-right font-mono text-[10px] opacity-60">{p.displayDate}</div>
    </div>
    <div className="flex-1 flex flex-col gap-1.5 overflow-hidden">
      {p.trendingData.slice(0, 12).map((item, idx) => (
        <div key={item.id || idx} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/10 backdrop-blur-md px-3 py-1.5">
          <span className="w-5 font-mono text-xs font-black opacity-50">{pad(idx)}</span>
          <span className="flex-1 text-sm font-bold tracking-tight truncate">{item.title}</span>
          <span className="rounded-md px-1.5 py-0.5 text-[10px] font-mono font-black" style={{ backgroundColor: p.theme.accentColor + "22", color: p.theme.accentColor }}>
            {formatStars(item.stars || "")}
          </span>
        </div>
      ))}
    </div>
    <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/10 backdrop-blur-md px-3 py-2">
      <span className="text-[9px] font-black tracking-widest uppercase opacity-60">@{p.authorName}</span>
      <span className="font-mono text-[9px] uppercase tracking-widest opacity-50">{p.timeText}</span>
    </div>
  </div>
);

const Chat: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#0f172a", color: "#ffffff" })}>
    <div className="flex items-center gap-3 px-4 py-3 bg-white/[0.05] border-b border-white/10">
      <div className="w-9 h-9 rounded-full bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center text-sm">⭐</div>
      <div className="flex-1">
        <div className="text-[13px] font-black leading-none">Trending Notify</div>
        <div className="text-[9px] text-emerald-400 mt-1">● 实时推送中</div>
      </div>
      <span className="px-2 py-0.5 rounded-full bg-red-500 text-[9px] font-bold">{p.trendingData.length}</span>
    </div>
    <div className="flex-1 flex flex-col gap-2.5 px-4 py-4 overflow-hidden">
      {p.trendingData.slice(0, 6).map((item, idx) => (
        <div key={item.id || idx} className="flex gap-2 items-end">
          <div className="w-6 h-6 rounded-full bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center text-[9px]">⭐</div>
          <div className="max-w-[80%] rounded-2xl rounded-bl-sm bg-white/10 border border-white/10 px-3 py-2">
            <div className="text-[10px] font-bold text-cyan-300">#{pad(idx)} 今日热榜</div>
            <div className="text-[11px] font-bold mt-0.5">{item.title}</div>
            <div className="font-mono text-[9px] opacity-60 mt-1">★{formatStars(item.stars || "")} · 今日 +{item.starsToday || "0"}</div>
          </div>
        </div>
      ))}
    </div>
    <div className="px-4 py-3 border-t border-white/10 flex justify-between text-[9px] text-zinc-500">
      <span>已读 · {p.displayDate} {p.timeText}</span>
      <span className="font-mono">@{p.authorName}</span>
    </div>
  </div>
);

const Neon: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%] relative", { backgroundColor: "#05050c", color: "#ffffff" })}>
    <div className="absolute -top-20 -left-20 w-64 h-64 rounded-full bg-cyan-500/20 blur-[80px] pointer-events-none" />
    <div className="absolute -bottom-24 -right-16 w-72 h-72 rounded-full bg-fuchsia-500/20 blur-[90px] pointer-events-none" />
    <div className="relative">
      <div className="flex items-center justify-between mb-2">
        <span className="font-mono text-[9px] tracking-[0.35em] uppercase text-cyan-300 [text-shadow:0_0_12px_rgba(34,211,238,0.9)]">Daily Ranking</span>
        <span className="font-mono text-[9px] text-zinc-500">{p.displayDate.slice(0, 6)}</span>
      </div>
      <h2 className="text-4xl font-black tracking-tighter bg-gradient-to-r from-cyan-300 via-white to-fuchsia-400 bg-clip-text text-transparent [filter:drop-shadow(0_0_18px_rgba(34,211,238,0.55))]">
        GITHUB<br />TRENDING
      </h2>
      <div className="mt-2 h-px w-full bg-gradient-to-r from-cyan-400/60 via-white/20 to-fuchsia-400/60" />
    </div>
    <div className="relative flex-1 flex flex-col gap-3 py-3">
      {p.trendingData.slice(0, 8).map((item, idx) => (
        <div key={item.id || idx} className="flex items-center gap-3">
          <span className="text-2xl font-black font-mono text-cyan-300" style={{ opacity: idx === 0 ? 1 : 0.5, textShadow: idx === 0 ? "0 0 14px rgba(34,211,238,0.9)" : undefined }}>
            {pad(idx)}
          </span>
          <span className="flex-1 text-[16px] font-bold truncate">{item.title}</span>
          <span className="text-[13px] font-mono font-bold text-fuchsia-300" style={{ opacity: idx === 0 ? 1 : 0.6 }}>{formatStars(item.stars || "")}</span>
        </div>
      ))}
    </div>
    <div className="relative flex justify-between pt-3 border-t border-white/10 text-[9px] uppercase tracking-widest text-zinc-500">
      <span className="font-bold">@{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Newspaper: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%]", { backgroundColor: "#f5f1e6", color: "#191512" })}>
    <div className="text-center">
      <h2 className="text-[28px] font-black tracking-[0.08em]" style={{ fontFamily: "Georgia, serif" }}>THE DAILY REPO</h2>
      <div className="mt-1.5 border-y-2 border-[#191512] py-1 flex justify-between font-mono text-[8px] uppercase tracking-widest opacity-70">
        <span>Vol.1 · No.{p.trendingData.length}</span><span>{p.displayDate}</span><span>FREE</span>
      </div>
    </div>
    <div className="mt-4">
      <div className="text-[20px] font-black leading-tight" style={{ fontFamily: "Georgia, serif" }}>{p.trendingData[0]?.title.split("/")[1]} 领跑今日热榜</div>
      <p className="text-[11px] leading-relaxed mt-1.5 opacity-80">{p.trendingData[0]?.content || ""}</p>
      <div className="mt-2 h-px bg-[#191512]/40" />
    </div>
    <div className="mt-2 flex-1">
      <div className="text-[9px] font-black tracking-[0.25em] uppercase mb-1.5">Briefs · 简讯</div>
      <div className="flex flex-col justify-between flex-1 gap-1">
        {p.trendingData.slice(1, 8).map((item, idx) => (
          <div key={item.id || idx} className="flex items-baseline gap-1 text-[10px]">
            <span className="font-mono font-bold">{pad(idx + 1)}</span>
            <span className="flex-1 truncate">{item.title}</span>
            <span className="font-mono">{formatStars(item.stars || "")}★</span>
          </div>
        ))}
      </div>
    </div>
    <div className="mt-3 pt-2 border-t-2 border-[#191512] flex justify-between text-[8px] uppercase tracking-widest opacity-70">
      <span className="font-bold">Edited by @{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Minimal: Variant = (p) => (
  <div {...base(p, "items-center px-[9%] py-[9%]", { backgroundColor: "#ffffff", color: "#18181b" })}>
    <span className="font-mono text-[9px] tracking-[0.35em] uppercase opacity-40">GitHub Trending</span>
    <div className="flex-1 flex flex-col items-center justify-center">
      <div className="text-[88px] font-black leading-none tracking-tighter">{p.trendingData.length}</div>
      <div className="font-mono text-[10px] tracking-[0.3em] uppercase opacity-40 mt-2">Projects Today</div>
      <div className="w-10 h-[2px] bg-zinc-900 mt-6" />
      <div className="mt-6 space-y-3">
        {p.trendingData.slice(0, 3).map((item, idx) => (
          <div key={item.id || idx} className="flex gap-3 text-[14px]">
            <span className="font-mono opacity-40">{pad(idx)}</span>
            <span className="font-semibold">{item.title.split("/")[1] || item.title}</span>
            <span className="font-mono opacity-50 ml-auto">{formatStars(item.stars || "")}</span>
          </div>
        ))}
      </div>
    </div>
    <div className="flex justify-between w-full text-[8px] uppercase tracking-[0.25em] opacity-40">
      <span>@{p.authorName}</span>
      <span className="font-mono">{p.displayDate.slice(5)}</span>
    </div>
  </div>
);

const Notebook: Variant = (p) => (
  <div {...base(p, "px-[8%] py-[7%] relative", { backgroundColor: "#fbf7ef", color: "#3a332b" })}>
    <div className="absolute top-0 left-6 w-24 h-6 bg-amber-200/90 -rotate-6" />
    <div className="absolute top-0 right-6 w-20 h-6 bg-rose-200/90 rotate-3" />
    <h2 className="text-[34px] leading-none mt-4" style={{ fontFamily: "'Caveat', cursive" }}>今日 GitHub 爆火</h2>
    <div className="font-mono text-[9px] opacity-50 mt-1">{p.displayDate} · 手账</div>
      <div className="flex-1 flex flex-col gap-3 mt-4">
      {p.trendingData.slice(0, 8).map((item, idx) => (
        <div key={item.id || idx} className="flex items-center gap-2 text-[15px]">
          <span className="w-4 h-4 border-2 border-[#3a332b]/60 rounded-[3px]" />
          <span className="flex-1 font-bold">{item.title}</span>
          <span className="font-mono text-[12px] opacity-60">{formatStars(item.stars || "")}★</span>
        </div>
      ))}
    </div>
    <div className="flex gap-2 mt-4">
      <span className="px-2 py-1 rounded bg-amber-200/70 -rotate-3 text-[10px] font-bold">AI 火🔥</span>
      <span className="px-2 py-1 rounded bg-emerald-200/70 rotate-2 text-[10px] font-bold">涨粉神器</span>
    </div>
    <div className="mt-3 text-[20px] opacity-60" style={{ fontFamily: "'Caveat', cursive" }}>—— @{p.authorName} 记</div>
  </div>
);

const Timeline: Variant = (p) => (
  <div {...base(p, "px-[8%] py-[6%]", { backgroundColor: "#0d1117", color: "#ffffff" })}>
    <div className="flex justify-between items-center mb-4">
      <span className="text-[10px] font-black tracking-[0.25em] uppercase opacity-60">Timeline · {p.displayDate.slice(5)}</span>
      <span className="font-mono text-[9px] opacity-40">TOP {p.trendingData.length}</span>
    </div>
    <div className="flex-1 relative">
      <div className="absolute left-[9px] top-1 bottom-1 w-px bg-white/15" />
      <div className="flex flex-col gap-2.5 pl-8 h-full">
        {p.trendingData.slice(0, 8).map((item, idx) => (
          <div key={item.id || idx} className="relative flex items-center gap-2 text-[14px]">
            <span
              className="absolute -left-[26px] w-[19px] h-[19px] rounded-full border-4 border-[#0d1117]"
              style={{ backgroundColor: idx === 0 ? p.theme.accentColor : "rgba(255,255,255,0.25)", boxShadow: idx === 0 ? `0 0 0 2px ${p.theme.accentColor}55` : undefined }}
            />
            <span className="font-mono text-[12px] w-6" style={{ color: idx === 0 ? p.theme.accentColor : undefined, opacity: idx === 0 ? 1 : 0.6 }}>{pad(idx)}</span>
            <span className="flex-1 font-bold truncate">{item.title}</span>
            <span className="font-mono text-[12px] opacity-60">{formatStars(item.stars || "")}</span>
          </div>
        ))}
      </div>
    </div>
    <div className="flex justify-between pt-3 border-t border-white/10 text-[9px] uppercase tracking-widest opacity-50">
      <span className="font-bold">@{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Browser: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#f6f8fa", color: "#18181b" })}>
    <div className="bg-[#e8ecf0] px-3 pt-2">
      <div className="flex gap-1">
        <div className="rounded-t-lg bg-[#f6f8fa] px-3 py-1.5 text-[10px] font-bold border border-zinc-200 border-b-0">github.com/trending</div>
        <div className="rounded-t-lg bg-[#e8ecf0] px-3 py-1.5 text-[10px] text-zinc-500">⭐ stars</div>
      </div>
    </div>
    <div className="flex items-center gap-2 bg-[#e8ecf0] px-3 py-1.5 border-b border-zinc-200">
      <div className="flex-1 flex items-center gap-1.5 rounded-full bg-white border border-zinc-200 px-3 py-1 text-[9px] text-zinc-500">
        <span className="text-emerald-500">🔒</span> github.com/trending
      </div>
    </div>
    <div className="flex-1 flex flex-col gap-2 px-4 py-3 overflow-hidden">
      <div className="text-[10px] font-black text-zinc-500 uppercase">Trending today</div>
      {p.trendingData.slice(0, 5).map((item, idx) => (
        <div key={item.id || idx} className="rounded-lg border border-zinc-200 bg-white px-3 py-2">
          <div className="flex justify-between items-center">
            <span className="text-[11px] font-bold truncate">{item.title}</span>
            <span className="text-[9px] text-yellow-600">★ {formatStars(item.stars || "")}</span>
          </div>
          <div className="text-[9px] text-zinc-500 mt-0.5 truncate">{item.content}</div>
          <div className="text-[8px] text-emerald-600 mt-1">▲ {item.starsToday || "0"} stars today</div>
        </div>
      ))}
    </div>
    <div className="px-4 py-2 border-t border-zinc-200 bg-white text-[8px] text-zinc-400 flex justify-between">
      <span>generated by @{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const GithubUI: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#ffffff", color: "#18181b" })}>
    <div className="px-4 py-3 border-b border-zinc-200">
      <div className="text-[12px] font-black">Trending Today</div>
      <div className="text-[9px] text-zinc-500 mt-0.5">{p.trendingData.length} open · {p.displayDate}</div>
    </div>
    <div className="flex-1 flex flex-col overflow-hidden">
      {p.trendingData.slice(0, 6).map((item, idx) => (
        <div key={item.id || idx} className="flex items-start gap-2 px-4 py-2 border-b border-zinc-100">
          <span className="mt-0.5 w-2 h-2 rounded-full bg-emerald-500" />
          <div className="min-w-0 flex-1">
            <div className="text-[11px] font-bold truncate">{item.title}</div>
            <div className="text-[9px] text-zinc-500 mt-0.5">
              <span className="text-emerald-600 font-bold">▲ +{item.starsToday || "0"}</span> stars · <span className="font-mono">#{pad(idx)}</span>
            </div>
          </div>
          <span className="text-[8px] font-mono text-zinc-400">{formatStars(item.stars || "")}★</span>
        </div>
      ))}
    </div>
    <div className="px-4 py-2 border-t border-zinc-200 flex justify-between text-[8px] text-zinc-400">
      <span>PR by @{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Cinema: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#0b0b0d", color: "#ffffff" })}>
    <div className="flex items-center justify-between px-6 pt-4 text-[8px] uppercase tracking-[0.3em] text-zinc-500">
      <span>★ ★ ★ ★ ★</span>
      <span className="font-mono">{p.displayDate.slice(0, 4)}</span>
    </div>
    <div className="flex-1 flex flex-col items-center justify-center px-6 text-center">
      <div className="text-[9px] font-black tracking-[0.4em] uppercase" style={{ color: p.theme.accentColor }}>A GitHub Production</div>
      <h2 className="text-[42px] font-black leading-none tracking-tight mt-4">TRENDING</h2>
      <div className="text-[10px] tracking-[0.35em] uppercase text-zinc-400 mt-2">Top {p.trendingData.length} Projects</div>
      <div className="w-12 h-[2px] my-5" style={{ backgroundColor: p.theme.accentColor }} />
      <div className="space-y-1.5 text-[10px] text-zinc-300">
        {p.trendingData.slice(0, 5).map((item, idx) => (
          <div key={item.id || idx}>
            {pad(idx)} <span className="text-white font-bold">{item.title}</span>
          </div>
        ))}
      </div>
    </div>
    <div className="border-t border-white/10 px-6 py-3 flex justify-between text-[8px] uppercase tracking-[0.25em] text-zinc-500">
      <span>Starring · Top {p.trendingData.length}</span>
      <span className="font-mono">@{p.authorName}</span>
    </div>
  </div>
);

const Hud: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%] relative", { backgroundColor: "#020a10", color: "#a5f3fc" })}>
    <div className="absolute inset-0 opacity-[0.07] pointer-events-none" style={{ background: "repeating-linear-gradient(0deg, transparent 0 2px, #22d3ee 2px 3px)" }} />
    <div className="relative flex justify-between items-center mb-3">
      <span className="font-mono text-[9px] tracking-[0.3em] uppercase">SYS.TRENDING</span>
      <span className="font-mono text-[9px] opacity-60">DATA {p.displayDate}</span>
    </div>
    <div className="relative flex-1 flex flex-col gap-2.5 py-1">
      {p.trendingData.slice(0, 8).map((item, idx) => (
        <div key={item.id || idx} className={`flex items-center gap-2.5 px-2.5 py-1.5 ${idx === 0 ? "border border-cyan-400/25 bg-cyan-400/5 rounded" : ""}`}>
          <span className="font-mono text-[14px]" style={{ color: idx === 0 ? "#67e8f9" : undefined, opacity: idx === 0 ? 1 : 0.6 }}>{pad(idx)}</span>
          <span className="flex-1 text-[14px] truncate" style={{ opacity: idx === 0 ? 1 : 0.8 }}>{item.title}</span>
          <span className="font-mono text-[12px]" style={{ opacity: idx === 0 ? 1 : 0.6 }}>★{formatStars(item.stars || "")}</span>
          <span className="font-mono text-[12px] text-emerald-300" style={{ opacity: idx === 0 ? 1 : 0.6 }}>+{item.starsToday || "0"}</span>
        </div>
      ))}
    </div>
    <div className="relative flex justify-between pt-2.5 border-t border-cyan-400/20 font-mono text-[8px] uppercase tracking-widest opacity-60">
      <span>Operator: @{p.authorName}</span>
      <span>{p.timeText}</span>
    </div>
  </div>
);

const Pixel: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%]", { backgroundColor: "#1b1b3a", color: "#f4f4f4", fontFamily: "'Press Start 2P', monospace" })}>
    <div className="flex justify-between items-center text-[8px] text-[#ffd23f]">
      <span>DAILY RANKING</span>
      <span>{p.displayDate.slice(5)}</span>
    </div>
    <h2 className="text-[24px] leading-tight text-[#ffd23f] mt-3 [text-shadow:3px_3px_0_#000]">GITHUB<br />TRENDING</h2>
    <div className="flex-1 flex flex-col gap-2 py-2 mt-2">
      {p.trendingData.slice(0, 6).map((item, idx) => (
        <div key={item.id || idx} className={`flex items-center gap-2 px-2 py-1.5 [box-shadow:4px_4px_0_#000] ${idx === 0 ? "bg-[#ffd23f] text-[#1b1b3a]" : "border-2 border-[#ffd23f]"}`}>
          <span className="text-[10px]" style={{ color: idx === 0 ? undefined : "#ffd23f" }}>{idx === 0 ? "1UP" : pad(idx)}</span>
          <span className="flex-1 text-[9px] truncate">{item.title}</span>
          <span className="text-[9px] text-[#7ee787]">{formatStars(item.stars || "")}★</span>
        </div>
      ))}
    </div>
    <div className="flex justify-between text-[7px] text-[#8b8bd4] pt-2 border-t-2 border-[#ffd23f]">
      <span>@{p.authorName}</span>
      <span>{p.timeText}</span>
    </div>
  </div>
);

const Ticket: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#fdf6ec", color: "#2a2118" })}>
    <div className="flex flex-1 min-h-0">
      <div className="w-[28%] border-r-2 border-dashed border-[#2a2118]/40 flex flex-col items-center justify-center gap-3 px-2 text-center">
        <span className="font-mono text-[8px] uppercase tracking-widest opacity-60">Admit<br />One</span>
        <span className="text-[34px] font-black font-mono">{p.trendingData.length}</span>
        <span className="text-[7px] uppercase tracking-widest opacity-50">Top Projects</span>
      </div>
      <div className="flex-1 flex flex-col px-4 py-4 min-w-0">
        <div className="text-[9px] font-black tracking-[0.2em] uppercase opacity-60">GitHub Trending</div>
        <div className="font-mono text-[8px] opacity-50 mt-0.5">{p.displayDate} · {p.timeText}</div>
        <div className="mt-3 flex-1 space-y-1.5 overflow-hidden">
          {p.trendingData.slice(0, 6).map((item, idx) => (
            <div key={item.id || idx} className="flex justify-between text-[10px]">
              <span className="font-bold truncate">{pad(idx)} {item.title}</span>
              <span className="font-mono opacity-70">{formatStars(item.stars || "")}★</span>
            </div>
          ))}
        </div>
        <div className="mt-3 pt-2 border-t border-[#2a2118]/30 flex justify-between text-[9px] font-bold">
          <span>SEAT: TOP-{p.trendingData.length}</span>
          <span className="font-mono">@{p.authorName}</span>
        </div>
      </div>
    </div>
    <div className="border-t-2 border-dashed border-[#2a2118]/40 h-0" />
    <div className="px-4 py-2.5 flex justify-center">
      <div className="h-7 w-[75%] opacity-80" style={{ background: "repeating-linear-gradient(90deg, #2a2118 0 2px, transparent 2px 5px)" }} />
    </div>
  </div>
);

const Sign: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#e8ecf1", color: "#ffffff" })}>
    <div className="w-full h-full rounded-2xl border-4 border-white p-[5%] flex flex-col" style={{ backgroundColor: "#0b6b3a" }}>
      <div className="flex items-center justify-between">
        <span className="text-[9px] font-black tracking-[0.25em] uppercase opacity-80">GitHub Trending</span>
        <span className="text-[9px] font-black tracking-[0.25em] uppercase opacity-80">{p.trendingData.length}</span>
      </div>
      <div className="flex-1 flex flex-col justify-center gap-1">
        {p.trendingData.slice(0, 5).map((item, idx) => (
          <div key={item.id || idx} className={`flex items-center gap-2 ${idx === 0 ? "border-b border-white/25 pb-2" : "border-b border-white/25 py-1.5"}`}>
            <span className={`font-black leading-none ${idx === 0 ? "text-[26px]" : "text-[20px] opacity-70"}`}>{pad(idx)}</span>
            <span className={`flex-1 font-bold truncate ${idx === 0 ? "text-[13px]" : "text-[12px] opacity-90"}`}>{item.title}</span>
            <span className={`font-mono ${idx === 0 ? "text-[10px] opacity-80" : "text-[9px] opacity-70"}`}>{formatStars(item.stars || "")}★</span>
          </div>
        ))}
      </div>
      <div className="flex items-center justify-between pt-2.5 border-t border-white/40 text-[9px] font-black tracking-[0.2em] uppercase">
        <span>★ Next Exit · Top{p.trendingData.length}</span>
        <span className="font-mono">@{p.authorName}</span>
      </div>
    </div>
  </div>
);

const Toc: Variant = (p) => (
  <div {...base(p, "px-[9%] py-[8%]", { backgroundColor: "#2a1f3d", color: "#f0e9d8" })}>
    <div className="text-[8px] font-black tracking-[0.35em] uppercase opacity-60">2026 · Vol.1</div>
    <h2 className="text-[28px] font-black leading-tight mt-2" style={{ fontFamily: "Georgia, serif" }}>今日开源<br />爆款名录</h2>
    <div className="mt-3 h-px w-full bg-[#f0e9d8]/30" />
    <div className="mt-3 text-[9px] font-black tracking-[0.3em] uppercase text-amber-300/90">Contents</div>
    <div className="flex-1 flex flex-col justify-between py-2">
      {p.trendingData.slice(0, 7).map((item, idx) => (
        <div key={item.id || idx} className="flex items-baseline gap-2 text-[11px]">
          <span className="font-black" style={{ fontFamily: "Georgia, serif" }}>{["壹", "贰", "叁", "肆", "伍", "陆", "柒"][idx]}</span>
          <span className="flex-1 truncate">{item.title}</span>
          <span className="font-mono text-[9px] opacity-60">{formatStars(item.stars || "")}★</span>
        </div>
      ))}
    </div>
    <div className="pt-3 border-t border-[#f0e9d8]/30 flex justify-between text-[9px] uppercase tracking-[0.25em] opacity-70">
      <span>@{p.authorName} 编</span>
      <span className="font-mono">P.{p.trendingData.length}</span>
    </div>
  </div>
);

const Notify: Variant = (p) => (
  <div {...base(p, "gap-2.5 px-[6%] py-[6%]", { background: "linear-gradient(to bottom, #14171c, #0b0d10)", color: "#ffffff" })}>
    <div className="text-center text-[9px] font-mono text-zinc-500">{p.displayDate} {p.timeText}</div>
    {p.trendingData.slice(0, 5).map((item, idx) => (
      <div key={item.id || idx} className="rounded-2xl bg-white/10 backdrop-blur-md border border-white/10 p-3 flex items-center gap-3">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center text-sm" style={{ background: `linear-gradient(135deg, ${p.theme.accentColor}, ${p.theme.textColor})` }}>
          {["🔥", "⚡", "🧠", "🚀", "📚"][idx] || "⭐"}
        </div>
        <div className="min-w-0 flex-1">
          <div className="text-[10px] font-bold" style={{ color: p.theme.accentColor }}>#{pad(idx)} 今日热榜</div>
          <div className="text-[11px] font-bold truncate mt-0.5">{item.title}</div>
          <div className="text-[9px] text-zinc-400 mt-0.5">+{item.starsToday || "0"} stars today</div>
        </div>
      </div>
    ))}
    <div className="flex-1" />
    <div className="text-center text-[9px] text-zinc-500 font-mono">@{p.authorName} · Trending Notify</div>
  </div>
);

const Receipt: Variant = (p) => (
  <div {...base(p, "font-mono", { backgroundColor: "#fbfaf6", color: "#1d1d1d" })}>
    <div className="px-6 pt-5 text-center">
      <div className="text-[13px] font-black tracking-[0.2em]">GITHUB TRENDING</div>
      <div className="text-[8px] opacity-60 mt-1">RECEIPT · {p.displayDate} · {p.timeText}</div>
      <div className="mt-2 border-t border-dashed border-zinc-400" />
    </div>
    <div className="flex-1 px-6 py-3 space-y-[7px] overflow-hidden">
      {p.trendingData.slice(0, 8).map((item, idx) => (
        <div key={item.id || idx} className="flex justify-between text-[10px]">
          <span className="truncate">{pad(idx)} {item.title}</span>
          <span>{formatStars(item.stars || "")}★</span>
        </div>
      ))}
      <div className="border-t border-dashed border-zinc-400 pt-1.5" />
      <div className="flex justify-between text-[11px] font-bold">
        <span>TOTAL STARS</span>
        <span>{p.trendingData.slice(0, 8).reduce((sum, i) => sum + (parseFloat(String(i.stars).replace(/k/gi, "").replace(/,/g, "")) || 0), 0)}k</span>
      </div>
      <div className="flex justify-between text-[10px] opacity-70">
        <span>支付方式</span>
        <span>STAR ⭐</span>
      </div>
      <div className="border-t border-dashed border-zinc-400 pt-1.5" />
      <div className="text-center text-[9px] opacity-70">谢谢支持开源 ❤️ @{p.authorName}</div>
    </div>
    <div className="px-6 pb-4 flex justify-center">
      <div className="h-6 w-[70%] opacity-70" style={{ background: "repeating-linear-gradient(90deg, #1d1d1d 0 2px, transparent 2px 5px)" }} />
    </div>
  </div>
);

const Aurora: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%] relative", { backgroundColor: "#060b18", color: "#ffffff" })}>
    <div className="absolute -top-10 -left-10 w-64 h-64 rounded-full bg-cyan-400/30 blur-[90px]" />
    <div className="absolute top-1/3 -right-16 w-72 h-72 rounded-full bg-emerald-400/25 blur-[100px]" />
    <div className="absolute -bottom-16 left-1/4 w-72 h-72 rounded-full bg-violet-500/30 blur-[100px]" />
    <div className="relative flex justify-between items-center">
      <span className="text-[9px] font-black tracking-[0.3em] uppercase opacity-70">Daily Ranking</span>
      <span className="font-mono text-[9px] opacity-50">{p.displayDate.slice(0, 6)}</span>
    </div>
    <h2 className="relative text-3xl font-black tracking-tight mt-2">
      GitHub <span className="bg-gradient-to-r from-cyan-300 to-emerald-300 bg-clip-text text-transparent">Trending</span>
    </h2>
    <div className="relative flex-1 flex flex-col gap-3 py-3">
      {p.trendingData.slice(0, 6).map((item, idx) => (
        <div key={item.id || idx} className={`flex items-center gap-3 rounded-2xl border border-white/15 px-3 py-2 ${idx === 0 ? "bg-white/10 backdrop-blur-md" : "bg-white/[0.06]"}`}>
          <span className="font-mono text-base font-black text-cyan-200" style={{ opacity: idx === 0 ? 1 : 0.6 }}>{pad(idx)}</span>
          <span className="flex-1 text-[15px] font-bold truncate" style={{ opacity: idx === 0 ? 1 : 0.9 }}>{item.title}</span>
          <span className="font-mono text-[12px] opacity-80">{formatStars(item.stars || "")}</span>
        </div>
      ))}
    </div>
    <div className="relative flex justify-between pt-3 border-t border-white/10 text-[9px] uppercase tracking-widest opacity-60">
      <span className="font-bold">@{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Cyber: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%] relative", { backgroundColor: "#080a12", color: "#d6ffe0" })}>
    <div className="absolute inset-0 opacity-[0.05]" style={{ background: "linear-gradient(#22d3ee 1px, transparent 1px), linear-gradient(90deg, #22d3ee 1px, transparent 1px)", backgroundSize: "36px 36px" }} />
    <span className="absolute top-3 left-3 w-6 h-6 border-t-2 border-l-2 border-cyan-400" />
    <span className="absolute top-3 right-3 w-6 h-6 border-t-2 border-r-2 border-cyan-400" />
    <span className="absolute bottom-3 left-3 w-6 h-6 border-b-2 border-l-2 border-fuchsia-400" />
    <span className="absolute bottom-3 right-3 w-6 h-6 border-b-2 border-r-2 border-fuchsia-400" />
    <div className="relative flex justify-between items-center">
      <span className="font-mono text-[9px] tracking-[0.3em] uppercase text-cyan-300">// trending.log</span>
      <span className="font-mono text-[9px] text-fuchsia-300">{p.displayDate}</span>
    </div>
    <h2 className="relative mt-3 text-3xl font-black tracking-tight [text-shadow:0_0_18px_rgba(34,211,238,0.5)]">GITHUB<br />TRENDING</h2>
    <div className="relative flex-1 flex flex-col gap-3 py-3">
      {p.trendingData.slice(0, 5).map((item, idx) => (
        <div key={item.id || idx} className={`flex items-center gap-2.5 px-3 ${idx === 0 ? "py-2 border border-cyan-400/30 bg-cyan-400/5" : "py-1.5"}`}>
          <span className="font-mono text-base font-black text-cyan-300" style={{ opacity: idx === 0 ? 1 : 0.5 }}>{pad(idx)}</span>
          <span className="flex-1 text-[15px] font-bold truncate" style={{ opacity: idx === 0 ? 1 : 0.8 }}>{item.title}</span>
          <span className="font-mono text-[12px] text-fuchsia-300" style={{ opacity: idx === 0 ? 1 : 0.5 }}>{formatStars(item.stars || "")}★</span>
        </div>
      ))}
    </div>
    <div className="relative flex justify-between pt-2.5 border-t border-cyan-400/30 font-mono text-[8px] uppercase tracking-widest text-cyan-300/70">
      <span>op: @{p.authorName}</span>
      <span>{p.timeText}</span>
    </div>
  </div>
);

const Glitch: Variant = (p) => (
  <div {...base(p, "px-[7%] py-[6%] relative", { backgroundColor: "#0d0d12", color: "#ffffff" })}>
    <div className="absolute inset-x-0 top-[38%] h-[3px] bg-white/10 mix-blend-screen" />
    <div className="absolute inset-x-0 top-[62%] h-[2px] bg-cyan-400/20 mix-blend-screen" />
    <div className="relative flex justify-between font-mono text-[9px] tracking-[0.25em] uppercase opacity-60">
      <span>ERR.TRENDING</span>
      <span>{p.displayDate.slice(5)}</span>
    </div>
    <h2 className="relative mt-3 text-[32px] font-black tracking-tighter">
      <span className="absolute inset-0 text-cyan-400/70 translate-x-[2px]">GITHUB<br />TRENDING</span>
      <span className="absolute inset-0 text-fuchsia-400/70 -translate-x-[2px]">GITHUB<br />TRENDING</span>
      <span className="relative">GITHUB<br />TRENDING</span>
    </h2>
    <div className="relative flex-1 flex flex-col gap-3 py-3">
      {p.trendingData.slice(0, 5).map((item, idx) => (
        <div key={item.id || idx} className={`flex items-center gap-2.5 px-3 ${idx === 0 ? "py-2 border border-white/15 bg-white/[0.04]" : "py-1.5"}`}>
          <span className="font-mono text-base font-black text-cyan-300" style={{ opacity: idx === 0 ? 1 : 0.5 }}>{pad(idx)}</span>
          <span className="flex-1 text-[15px] font-bold truncate" style={{ opacity: idx === 0 ? 1 : 0.8 }}>{item.title}</span>
          <span className="font-mono text-[12px] opacity-80">{formatStars(item.stars || "")}★</span>
        </div>
      ))}
    </div>
    <div className="relative flex justify-between pt-2.5 border-t border-white/15 font-mono text-[8px] uppercase tracking-widest opacity-60">
      <span>@{p.authorName}</span>
      <span>{p.timeText}</span>
    </div>
  </div>
);

const Bauhaus: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#f3f0e8", color: "#111111" })}>
    <div className="absolute top-0 right-0 w-32 h-32 bg-red-500 rounded-bl-[3rem]" />
    <div className="absolute bottom-0 left-0 w-24 h-24 bg-yellow-400" />
    <div className="absolute bottom-8 left-10 w-16 h-16 rounded-full bg-blue-600" />
    <div className="relative flex-1 flex flex-col px-[8%] py-[7%]">
      <div className="flex justify-between items-start">
        <span className="bg-black text-white px-2 py-1 text-[9px] font-black tracking-[0.2em] uppercase">Trending</span>
        <span className="font-mono text-[9px] opacity-60">{p.trendingData.length}</span>
      </div>
      <h2 className="text-4xl font-black tracking-tighter leading-[0.95] mt-5">GITHUB<br />DAILY</h2>
      <div className="w-14 h-[6px] bg-red-500 mt-4" />
      <div className="mt-5 space-y-2.5">
        {p.trendingData.slice(0, 4).map((item, idx) => (
          <div key={item.id || idx} className="flex gap-3 text-[12px] font-bold">
            <span className="font-mono">{pad(idx)}</span>
            <span className="flex-1 truncate">{item.title}</span>
            <span className="font-mono opacity-60">{formatStars(item.stars || "")}</span>
          </div>
        ))}
      </div>
    </div>
    <div className="relative flex justify-between px-[8%] pb-4 text-[9px] font-black uppercase tracking-[0.2em]">
      <span>@{p.authorName}</span>
      <span className="font-mono">{p.timeText}</span>
    </div>
  </div>
);

const Greeting: Variant = (p) => (
  <div {...base(p, "items-center px-[8%] py-[7%] relative", { backgroundColor: "#fdf9f0", color: "#8a6d2f" })}>
    <div className="absolute inset-3 rounded-[1.5rem] border border-[#d4b978] pointer-events-none" />
    <div className="text-[9px] font-black tracking-[0.4em] uppercase text-[#b3984f] mt-2">With Compliments</div>
    <div className="flex-1 flex flex-col items-center justify-center text-center">
      <div className="text-[38px] font-black" style={{ fontFamily: "Georgia, serif" }}>今日之星</div>
      <div className="mt-3 w-10 h-[2px] bg-[#d4b978]" />
      <div className="text-[20px] font-black mt-4" style={{ fontFamily: "Georgia, serif" }}>{p.trendingData[0]?.title.split("/")[1] || ""}</div>
      <div className="font-mono text-[9px] opacity-70 mt-1">{formatStars(p.trendingData[0]?.stars || "")} stars · +{p.trendingData[0]?.starsToday || "0"} today</div>
    </div>
    <div className="flex justify-between w-full text-[9px] font-black tracking-[0.25em] uppercase text-[#b3984f]">
      <span>@{p.authorName}</span>
      <span>{p.displayDate.slice(5)}</span>
    </div>
  </div>
);

const Infographic: Variant = (p) => {
  const top5 = p.trendingData.slice(0, 5);
  const max = Math.max(...top5.map((i) => parseFloat(String(i.stars).replace(/k/gi, "").replace(/,/g, "")) || 0), 1);
  const width = (s?: string) => `${Math.max(((parseFloat(String(s).replace(/k/gi, "").replace(/,/g, "")) || 0) / max) * 100, 2)}%`;
  return (
    <div {...base(p, "px-[8%] py-[7%]", { backgroundColor: "#ffffff", color: "#18181b" })}>
      <div className="flex justify-between items-center">
        <span className="font-mono text-[9px] tracking-[0.25em] uppercase opacity-50">GitHub Trending · {p.displayDate.slice(5)}</span>
        <span className="px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 text-[9px] font-bold">▲ 今日新增</span>
      </div>
      <div className="mt-4 grid grid-cols-3 gap-2 text-center">
        <div className="rounded-xl bg-zinc-50 border border-zinc-200 p-3"><div className="text-xl font-black">{p.trendingData.length}</div><div className="text-[8px] uppercase opacity-50 mt-1">Projects</div></div>
        <div className="rounded-xl bg-zinc-50 border border-zinc-200 p-3"><div className="text-xl font-black">{formatStars(String(Math.round(max)))}</div><div className="text-[8px] uppercase opacity-50 mt-1">Top ★</div></div>
        <div className="rounded-xl bg-zinc-50 border border-zinc-200 p-3"><div className="text-xl font-black text-emerald-600">+{top5.reduce((s, i) => s + (parseInt(String(i.starsToday).replace(/,/g, ""), 10) || 0), 0).toLocaleString()}</div><div className="text-[8px] uppercase opacity-50 mt-1">Today</div></div>
      </div>
      <div className="mt-5">
        <div className="text-[10px] font-black uppercase tracking-widest opacity-60 mb-2.5">Top 5 by stars</div>
        <div className="space-y-2.5">
          {top5.map((item, idx) => (
            <div key={item.id || idx}>
              <div className="flex justify-between text-[10px] font-bold mb-1">
                <span className="truncate">{item.title.split("/")[1] || item.title}</span>
                <span className="font-mono">{formatStars(item.stars || "")}</span>
              </div>
              <div className="h-[8px] rounded-full bg-zinc-100">
                <div className="h-full rounded-full" style={{ width: width(item.stars), backgroundColor: idx === 0 ? p.theme.accentColor : "#10b981" }} />
              </div>
            </div>
          ))}
        </div>
      </div>
      <div className="flex-1" />
      <div className="pt-3 border-t border-zinc-200 flex justify-between text-[9px] uppercase tracking-widest opacity-50">
        <span className="font-bold">@{p.authorName}</span>
        <span className="font-mono">{p.timeText}</span>
      </div>
    </div>
  );
};

const Pornhub: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#000000", color: "#ffffff" })}>
    <div className="flex items-center justify-center gap-1 py-2.5 border-b border-white/10 relative">
      <span className="text-[22px] font-black text-orange-500 tracking-tight">Github</span>
      <span className="text-[16px] font-black text-orange-500">▶</span>
      <span className="text-[22px] font-black text-orange-500 tracking-tight">hub</span>
      <span className="absolute right-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 border border-orange-500 text-orange-500 text-[8px] font-bold">HD</span>
      <span className="absolute left-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 bg-white/10 text-[8px] font-bold">1080P</span>
    </div>
    <div className="relative flex-1 flex items-center justify-center">
      <div className="absolute inset-0 bg-gradient-to-b from-zinc-900 to-black" />
      <div className="relative w-16 h-16 rounded-full bg-white/10 border border-white/20 flex items-center justify-center">
        <span className="text-2xl text-white/80 ml-1">▶</span>
      </div>
      <div className="absolute bottom-0 inset-x-0 px-4 pb-3">
        <div className="flex justify-between text-[10px] mb-1">
          <span className="font-bold">GitHub Trending Top {p.trendingData.length} - {p.displayDate}</span>
          <span className="font-mono text-orange-500">{p.timeText}</span>
        </div>
        <div className="h-1 rounded-full bg-white/20 overflow-hidden"><div className="h-full w-1/3 bg-orange-500" /></div>
      </div>
    </div>
    <div className="px-4 py-3 border-t border-white/10">
      <div className="text-[9px] font-black uppercase tracking-widest text-zinc-500 mb-2">Related · 相关推荐</div>
      <div className="space-y-1.5">
        {p.trendingData.slice(0, 3).map((item, idx) => (
          <div key={item.id || idx} className="flex items-center gap-2 text-[10px]">
            <span className="w-10 h-6 rounded bg-zinc-800 flex items-center justify-center text-[6px] text-orange-400">+{item.starsToday || "0"}</span>
            <span className="flex-1 truncate">{pad(idx)} {item.title}</span>
          </div>
        ))}
      </div>
    </div>
  </div>
);

const XPost: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#ffffff", color: "#0f1419" })}>
    <div className="px-4 pt-4 flex items-center gap-3">
      <div className="w-11 h-11 rounded-full bg-black text-white flex items-center justify-center text-lg font-black">𝕏</div>
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-1 text-[13px] font-black truncate">GitHub Trending <span className="text-[#1d9bf0]">✓</span></div>
        <div className="text-[11px] text-zinc-500">@githubtrending · 现在</div>
      </div>
      <span className="text-zinc-400 text-lg">⋯</span>
    </div>
    <div className="px-4 py-3 flex-1 min-h-0 overflow-hidden">
      <p className="text-[13px] leading-relaxed">今日 GitHub 爆火项目 Top{p.trendingData.length} 🔥</p>
      <div className="mt-2.5 space-y-1.5 font-mono text-[10px]">
        {p.trendingData.slice(0, 8).map((item, idx) => (
          <div key={item.id || idx} className="flex gap-2">
            <span className="text-zinc-400">{idx + 1}.</span>
            <span className={`flex-1 truncate ${idx === 0 ? "font-semibold" : ""}`}>{item.title}</span>
            <span className={idx === 0 ? "text-[#1d9bf0]" : "text-zinc-500"}>{formatStars(item.stars || "")}★</span>
          </div>
        ))}
      </div>
      <div className="mt-3 flex gap-1.5">
        <span className="px-2 py-0.5 rounded-full bg-[#e8f1fd] text-[#1d9bf0] text-[9px] font-bold">#GitHub</span>
        <span className="px-2 py-0.5 rounded-full bg-[#e8f1fd] text-[#1d9bf0] text-[9px] font-bold">#Trending</span>
      </div>
    </div>
    <div className="px-4 py-3 border-t border-zinc-100 flex justify-around text-[10px] text-zinc-500">
      <span>💬 {p.trendingData.length}</span><span>🔁 {formatStars(p.trendingData[0]?.stars || "")}</span><span className="text-[#f91880]">❤️ +{p.trendingData.reduce((s, i) => s + (parseInt(String(i.starsToday).replace(/,/g, ""), 10) || 0), 0).toLocaleString()}</span><span>📊 Top{p.trendingData.length}</span>
    </div>
  </div>
);

const Telegram: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#e7ebf0", color: "#111111" })}>
    <div className="flex items-center gap-2.5 px-3 py-2.5 bg-[#2aabee] text-white">
      <div className="w-8 h-8 rounded-full bg-white flex items-center justify-center text-[#2aabee] font-black text-sm">✈</div>
      <div className="flex-1">
        <div className="text-[12px] font-bold leading-none">GitHub Trending</div>
        <div className="text-[8px] opacity-80 mt-0.5">{p.trendingData.length} 条推送 · 刚刚</div>
      </div>
      <span className="text-lg">⋯</span>
    </div>
    <div className="flex-1 px-3 py-3 flex flex-col gap-2 overflow-hidden">
      {p.trendingData.slice(0, 5).map((item, idx) => (
        <div key={item.id || idx} className="max-w-[88%] rounded-xl rounded-tl-sm bg-white px-3 py-2 shadow-sm">
          <div className="text-[10px] font-bold text-[#2aabee]">GitHub Trending</div>
          <div className="text-[11px] leading-snug mt-0.5">
            {pad(idx)} · <b>{item.title}</b> — {formatStars(item.stars || "")}★ (+{item.starsToday || "0"})
          </div>
        </div>
      ))}
    </div>
    <div className="px-3 py-2.5 bg-white flex items-center gap-2">
      <div className="flex-1 rounded-full bg-[#e7ebf0] px-3 py-1.5 text-[10px] text-zinc-500">消息</div>
      <div className="w-7 h-7 rounded-full bg-[#2aabee] flex items-center justify-center text-white text-xs">➤</div>
    </div>
  </div>
);

const Instagram: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#ffffff", color: "#262626" })}>
    <div className="flex items-center gap-2.5 px-3 py-2.5">
      <div className="w-8 h-8 rounded-full p-[2px] bg-gradient-to-tr from-yellow-400 via-pink-500 to-purple-600">
        <img src="/my-avatar.jpg" alt="author" crossOrigin="anonymous" className="w-full h-full rounded-full object-cover" referrerPolicy="no-referrer" />
      </div>
      <div className="flex-1 text-[12px] font-bold truncate">{p.authorName}</div>
      <span className="text-lg text-zinc-500">⋯</span>
    </div>
    <div className="flex-1 flex items-center justify-center px-6 text-white" style={{ background: "linear-gradient(135deg, #405de6, #833ab4, #fd1d1d)" }}>
      <div className="text-center">
        <div className="text-[24px] font-black leading-tight">今日 GitHub<br />爆火 Top{p.trendingData.length}</div>
        <div className="text-[10px] opacity-80 mt-2">{p.trendingData.slice(0, 3).map((i) => i.title.split("/")[1]).join(" · ")} …</div>
      </div>
    </div>
    <div className="px-3 py-2.5">
      <div className="flex gap-3 text-xl"><span className="text-[#fd1d1d]">♥</span><span>💬</span><span>📤</span><span className="ml-auto">🔖</span></div>
      <div className="text-[11px] font-bold mt-1.5">{p.trendingData.reduce((s, i) => s + (parseInt(String(i.starsToday).replace(/,/g, ""), 10) || 0), 0).toLocaleString()} 次赞</div>
      <div className="text-[10px] mt-0.5">今日 Top{p.trendingData.length} 榜单更新啦 🚀</div>
      <div className="text-[10px] text-[#00376b] mt-0.5">#GitHub #Trending #开源 #开发者</div>
      <div className="text-[9px] text-zinc-400 mt-1">{p.timeText} · 查看全部 {p.trendingData.length} 条评论</div>
    </div>
  </div>
);

const Onlyfans: Variant = (p) => (
  <div {...base(p, "", { backgroundColor: "#0d1017", color: "#ffffff" })}>
    <div className="px-4 pt-4 flex items-center gap-3">
      <div className="w-12 h-12 rounded-full bg-[#0095f2] flex items-center justify-center text-xl font-black italic">G</div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1 text-[14px] font-black truncate">@{p.authorName} <span className="text-[#0095f2]">✓</span></div>
        <div className="text-[10px] text-zinc-500">{p.trendingData.length} 个开源项目 · 每日更新</div>
      </div>
    </div>
    <div className="px-4 mt-4">
      <div className="rounded-xl border border-[#0095f2]/40 bg-[#0095f2]/10 p-3.5">
        <div className="flex justify-between items-center gap-3">
          <div>
            <div className="text-[11px] font-black">GitHub 每日热榜</div>
            <div className="text-[9px] text-zinc-400 mt-0.5">免费订阅 · 每日 {p.timeText} 更新</div>
          </div>
          <span className="px-3 py-1.5 rounded-lg bg-[#0095f2] text-[10px] font-black shrink-0">SUBSCRIBE</span>
        </div>
      </div>
    </div>
    <div className="px-4 mt-4 flex-1 min-h-0 overflow-hidden">
      <div className="text-[9px] font-black uppercase tracking-widest text-zinc-500 mb-2">近期热门</div>
      <div className="space-y-2">
        {p.trendingData.slice(0, 4).map((item, idx) => (
          <div key={item.id || idx} className="flex items-center gap-2.5 rounded-lg bg-white/[0.04] border border-white/10 p-2.5">
            <span className="w-6 text-center text-[10px] font-black text-[#0095f2]" style={{ opacity: idx === 0 ? 1 : 0.6 }}>{idx + 1}</span>
            <span className="flex-1 text-[11px] font-bold truncate">{item.title}</span>
            <span className="text-[9px] text-zinc-500">{formatStars(item.stars || "")}★</span>
          </div>
        ))}
      </div>
    </div>
    <div className="px-4 py-3 flex justify-between text-[9px] text-zinc-500 border-t border-white/10">
      <span>OnlyFans · parody</span>
      <span className="font-mono">@{p.authorName}</span>
    </div>
  </div>
);

export const IndexVariants: Record<CardStyle, Variant> = {
  classic: Classic,
  poster: Poster,
  terminal: Terminal,
  magazine: Magazine,
  databar: Databar,
  cardstack: Cardstack,
  glass: Glass,
  chat: Chat,
  neon: Neon,
  newspaper: Newspaper,
  minimal: Minimal,
  notebook: Notebook,
  timeline: Timeline,
  browser: Browser,
  github: GithubUI,
  cinema: Cinema,
  hud: Hud,
  pixel: Pixel,
  ticket: Ticket,
  sign: Sign,
  toc: Toc,
  notify: Notify,
  receipt: Receipt,
  aurora: Aurora,
  cyber: Cyber,
  glitch: Glitch,
  bauhaus: Bauhaus,
  greeting: Greeting,
  infographic: Infographic,
  pornhub: Pornhub,
  x: XPost,
  telegram: Telegram,
  instagram: Instagram,
  onlyfans: Onlyfans,
};
