import React from "react";
import { Clock } from "lucide-react";
import { Theme, RankingItem } from "../types";
import { formatStars } from "../utils";

interface IndexCardProps {
  theme: Theme;
  displayDate: string;
  timeText: string;
  weekdayText: string;
  authorName: string;
  globalSummary: string;
  globalHashtags: string;
  trendingData: RankingItem[];
  setStatusMsg: (msg: string | null) => void;
}

export const IndexCard: React.FC<IndexCardProps> = ({
  theme,
  displayDate,
  timeText,
  weekdayText,
  authorName,
  globalSummary,
  globalHashtags,
  trendingData,
  setStatusMsg,
}) => {
  return (
    <div
      className="w-full aspect-[3/4] p-8 flex flex-col transition-all duration-500 shadow-2xl relative overflow-hidden"
      style={{
        background: theme.outerBg,
        color: theme.textColor,
      }}
    >
      <div
        className="flex-1 rounded-[2.5rem] p-8 flex flex-col shadow-inner relative overflow-hidden border border-white/10"
        style={{ background: theme.cardBg }}
      >
        {/* Header */}
        <div className="flex justify-between items-start mb-8">
          <div className="space-y-1">
            <div className="text-sm font-black tracking-widest opacity-40">
              {displayDate}
            </div>
            <div className="flex items-center gap-3">
              <div className="text-4xl font-black tracking-tighter tabular-nums">
                {timeText}
              </div>
              <div className="px-2 py-0.5 rounded-md bg-current/10 text-[10px] font-bold tracking-widest opacity-60">
                {weekdayText}
              </div>
            </div>
          </div>
          <div className="flex flex-col items-end">
            <div className="text-[10px] font-black uppercase tracking-widest opacity-30 mb-1">
              Generated by
            </div>
            <div className="flex items-center gap-2">
              <img
                src="/my-avatar.jpg"
                alt="author"
                className="w-6 h-6 rounded-full border border-current/20"
              />
              <span className="text-sm font-black tracking-tight">
                @{authorName}
              </span>
            </div>
          </div>
        </div>

        {/* Title */}
        <div className="mb-10">
          <h2 className="text-5xl font-black tracking-tighter leading-[0.9] mb-4">
            GITHUB
            <br />
            <span style={{ color: theme.accentColor }}>TRENDING</span>
          </h2>
          <div className="h-1.5 w-20 rounded-full" style={{ background: theme.accentColor }}></div>
        </div>

        {/* Global Summary */}
        <div className="mb-8 p-5 rounded-3xl bg-current/5 border border-current/5 relative">
          <div className="absolute -top-3 -left-2 px-3 py-1 rounded-full bg-white text-[10px] font-black tracking-widest shadow-sm border border-zinc-100 text-zinc-950">
            AI INSIGHT
          </div>
          <p className="text-sm font-bold leading-relaxed opacity-80 line-clamp-4">
            {globalSummary || "正在同步今日 GitHub 最热开源项目..."}
          </p>
        </div>

        {/* Projects List */}
        <div className="flex-1 space-y-2 overflow-hidden">
          {trendingData.slice(0, 15).map((item, i) => (
            <div
              key={i}
              className="flex items-center justify-between py-2 border-b border-current/5 last:border-0 group"
            >
              <div className="flex items-center gap-3 min-w-0">
                <span className="text-xs font-black opacity-20 w-4 tabular-nums">
                  {(i + 1).toString().padStart(2, "0")}
                </span>
                <span className="text-sm font-bold tracking-tight truncate group-hover:translate-x-1 transition-transform">
                  {item.title}
                </span>
              </div>
              <div className="flex items-center gap-2 shrink-0 ml-4">
                <div className="text-[10px] font-black opacity-40 uppercase tabular-nums">
                  {formatStars(item.stars || "")}
                </div>
                <div
                  className="text-[10px] font-bold tabular-nums px-1.5 py-0.5 rounded bg-current/5"
                  style={{ color: theme.accentColor }}
                >
                  +{formatStars(item.starsToday || "")}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 pt-6 border-t border-current/10 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Clock className="w-3 h-3 opacity-40" />
            <span className="text-[10px] font-bold uppercase tracking-widest opacity-40">
              Real-time Analysis
            </span>
          </div>
          <div className="text-[10px] font-black tracking-tighter opacity-20">
            GITHUB.COM/TRENDING
          </div>
        </div>
      </div>
    </div>
  );
};
