import React from "react";
import { Theme, RankingItem } from "../types";
import { formatStars } from "../utils";

interface IndexCardProps {
  theme: Theme;
  displayDate: string;
  timeText: string;
  authorName: string;
  trendingData: RankingItem[];
}

export const IndexCard: React.FC<IndexCardProps> = ({
  theme,
  displayDate,
  timeText,
  authorName,
  trendingData,
}) => {
  return (
    <div
      className="w-full h-full rounded-[3.5rem] relative overflow-hidden flex flex-col shadow-inner py-[4%] px-[4%]"
      style={{
        backgroundColor: theme.cardBg,
        color: theme.textColor,
      }}
    >
      {/* Index Mode Header */}
      <div className="mb-6 text-center">
        <div className="inline-block px-3 py-1 rounded-full bg-white/5 border border-white/10 text-[10px] font-black tracking-[0.2em] uppercase mb-3 opacity-60">
          Daily Ranking
        </div>
        <h2 className="text-3xl font-black tracking-tighter leading-none">
          GitHub Trending
        </h2>
        <p className="text-xs font-mono opacity-30 mt-2">
          TOP 15 PROJECTS • {displayDate}
        </p>
      </div>

      {/* Ranking List */}
      <div className="flex-1 flex flex-col justify-between py-1">
        {trendingData.slice(0, 15).map((item, idx) => (
          <div key={item.id || idx} className="flex items-center gap-3 group">
            <span className="w-6 text-base font-mono opacity-20 font-black">
              {(idx + 1).toString().padStart(2, "0")}
            </span>
            <span className="flex-1 text-base font-bold tracking-tight truncate">
              {item.title}
            </span>
            <span
              className="text-sm font-mono font-black"
              style={{
                color: idx < 3 ? theme.accentColor : "inherit",
                opacity: idx < 3 ? 1 : 0.3,
              }}
            >
              {formatStars(item.stars || "")} 今日:{item.starsToday || "0"}
            </span>
          </div>
        ))}
      </div>

      {/* Index Mode Footer */}
      <div className="mt-6 pt-6 border-t border-white/5 flex justify-between items-center">
        <div className="opacity-30">
          <div className="text-[10px] font-black tracking-widest uppercase">
            Generated by @{authorName}
          </div>
          <div className="font-mono text-[10px] uppercase tracking-widest">
            {timeText}
          </div>
        </div>
        <img
          src="/my-avatar.jpg"
          alt="author"
          crossOrigin="anonymous"
          className="w-20 h-20 rounded-full border-2 border-white/10 shadow-md object-cover"
          referrerPolicy="no-referrer"
        />
      </div>
    </div>
  );
};
