import { Template, RankingItem, CardStyle } from "./types";

export const CARD_STYLES: { id: CardStyle; name: string; desc: string }[] = [
  { id: "classic", name: "经典榜单", desc: "信息密度高" },
  { id: "poster", name: "大字报", desc: "抖音封面风" },
  { id: "terminal", name: "终端代码", desc: "开发者人设" },
  { id: "magazine", name: "杂志编辑", desc: "编辑感强" },
  { id: "databar", name: "数据条", desc: "星标可视化" },
  { id: "cardstack", name: "卡片流", desc: "产品感" },
  { id: "glass", name: "玻璃拟态", desc: "毛玻璃质感" },
  { id: "chat", name: "聊天对话", desc: "AI 通知流" },
  { id: "neon", name: "霓虹辉光", desc: "赛博夜店风" },
  { id: "newspaper", name: "报纸复古", desc: "纸媒感" },
  { id: "minimal", name: "极简留白", desc: "高级感" },
  { id: "notebook", name: "手账便签", desc: "纸胶带" },
  { id: "timeline", name: "时间轴", desc: "节点排行" },
  { id: "browser", name: "浏览器窗口", desc: "网页感" },
  { id: "github", name: "GitHub PR", desc: "合并绿勾" },
  { id: "cinema", name: "电影海报", desc: "卡司表" },
  { id: "hud", name: "科幻 HUD", desc: "扫描线读数" },
  { id: "pixel", name: "像素风", desc: "8-bit 复古" },
  { id: "ticket", name: "票据", desc: "入场券" },
  { id: "sign", name: "路牌", desc: "高速指示" },
  { id: "toc", name: "目录书页", desc: "精装书" },
  { id: "notify", name: "系统通知", desc: "锁屏堆叠" },
  { id: "receipt", name: "收据", desc: "热敏纸" },
  { id: "aurora", name: "极光渐变", desc: "流动光带" },
  { id: "cyber", name: "赛博边框", desc: "四角括号" },
  { id: "glitch", name: "故障风", desc: "RGB 错位" },
  { id: "bauhaus", name: "几何构成", desc: "包豪斯" },
  { id: "greeting", name: "贺卡", desc: "金边排印" },
  { id: "infographic", name: "信息图", desc: "数据可视化" },
  { id: "pornhub", name: "Githubhub", desc: "播放器梗图" },
  { id: "x", name: "X 推文", desc: "转发点赞" },
  { id: "telegram", name: "Telegram", desc: "蓝色频道" },
  { id: "instagram", name: "Instagram", desc: "帖子卡片" },
  { id: "onlyfans", name: "OnlyFans", desc: "订阅解锁" },
];

export const TEMPLATES: Template[] = [
  {
    id: "contrast-black",
    name: "高对比暗黑",
    desc: "经典开发者风格",
    theme: {
      outerBg: "#E7ECB0",
      cardBg: "#000000",
      textColor: "#FFFFFF",
      accentColor: "#FFEB3B",
    },
  },
  {
    id: "mint-note",
    name: "极简便签",
    desc: "清新生活方式",
    theme: {
      outerBg: "#BDF1E6",
      cardBg: "#A9EAD9",
      textColor: "#172033",
      accentColor: "#12664B",
    },
  },
  {
    id: "pink-pop",
    name: "糖果海报",
    desc: "活泼社交风格",
    theme: {
      outerBg: "#F37CB2",
      cardBg: "#F3F1F4",
      textColor: "#0F766E",
      accentColor: "#D6336C",
    },
  },
  {
    id: "sunny-card",
    name: "明快卡片",
    desc: "暖色调大标题",
    theme: {
      outerBg: "#F7B36C",
      cardBg: "#FAFAF7",
      textColor: "#734019",
      accentColor: "#B45309",
    },
  },
  {
    id: "ambient-sketch",
    name: "随笔氛围",
    desc: "柔和光影质感",
    theme: {
      outerBg: "#D1D5DB",
      cardBg: "#F9FAFB",
      textColor: "#1F2937",
      accentColor: "#2563EB",
    },
  },
  {
    id: "vibrant-melon",
    name: "活力瓜条",
    desc: "高饱和度趣味",
    theme: {
      outerBg: "#FF9F1C",
      cardBg: "#FFFFFF",
      textColor: "#0F766E",
      accentColor: "#E71D36",
    },
  },
  {
    id: "gradient-poster",
    name: "渐变海报",
    desc: "现代流体美学",
    theme: {
      outerBg: "#4F46E5",
      cardBg: "#FFFFFF",
      textColor: "#1E1B4B",
      accentColor: "#6366F1",
    },
  },
  {
    id: "minimal-paper",
    name: "简约纸条",
    desc: "素雅纸张触感",
    theme: {
      outerBg: "#E5E7EB",
      cardBg: "#FFFFFF",
      textColor: "#374151",
      accentColor: "#6B7280",
    },
  },
  {
    id: "cyber-neon",
    name: "赛博霓虹",
    desc: "未来主义科技感",
    theme: {
      outerBg: "#0F172A",
      cardBg: "#1E293B",
      textColor: "#38BDF8",
      accentColor: "#F472B6",
    },
  },
  {
    id: "retro-news",
    name: "复古报刊",
    desc: "经典排版美学",
    theme: {
      outerBg: "#F3E5AB",
      cardBg: "#FFFDD0",
      textColor: "#3D2B1F",
      accentColor: "#8B4513",
    },
  },
  {
    id: "deep-ocean",
    name: "深海沉静",
    desc: "静谧深邃质感",
    theme: {
      outerBg: "#0C4A6E",
      cardBg: "#082F49",
      textColor: "#BAE6FD",
      accentColor: "#38BDF8",
    },
  },
  {
    id: "sunset-glow",
    name: "落日余晖",
    desc: "温暖治愈色彩",
    theme: {
      outerBg: "#FF7E5F",
      cardBg: "#FEB47B",
      textColor: "#5F2C1F",
      accentColor: "#7C2D12",
    },
  },
  {
    id: "mono-bw",
    name: "黑白极简",
    desc: "纯粹黑白",
    theme: {
      outerBg: "#FFFFFF",
      cardBg: "#000000",
      textColor: "#FFFFFF",
      accentColor: "#E4E4E7",
    },
  },
];

export const GITHUB_TRENDING_MOCK: RankingItem[] = [];
